In [1]:
v1 = int(input('enter first value'))
v2 = int(input('enter second value'))

def addvar(v1+v2):
    return v1+v2

SyntaxError: invalid syntax (<ipython-input-1-40f67b7e96e6>, line 4)

In [ ]:
addvar(2,3)

In [3]:
1+'p'

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [4]:
'p'+1

TypeError: can only concatenate str (not "int") to str

In [7]:
word = 'Data Scienc'

print('s' in word)


False


In [2]:
l1 = [10, 20, 33, 46, 55]

l1 = list(filter(lambda x: x%5 == 0,l1))
print(l1)

[10, 20, 55]


In [ ]:
a1 = int(input('enter first value'))
b1 = int(input('enter second value'))

def addsub(a1,b1):
    return a1+b1, a1-b1

In [ ]:
addsub(2,3)

## Assignment - 3

In [24]:
from zmy_pkg import maths

In [25]:
maths.calc.factorial(5)

120

In [26]:
maths.calc.degree_cel(32)

89.6

In [50]:

def fibonacci(n):
    a=0
    b=1
    count = 0
    if n<0:
        print('wrong input')
    elif n==0:
        return 0
    elif n==1:
        return 1
    else:
        while count < n:  
            print(a)  
            c = a + b  
            a = b  
            b = c  
            count += 1 

In [51]:
fibonacci(9)

0
1
1
2
3
5
8
13
21


In [55]:
l1 = list(range(10))

iter1 = reversed(l1)

for i in range(len(l1)):
    print(next(iter1))

9
8
7
6
5
4
3
2
1
0


### Assignment 3

In [1]:
# Create a 2D array and print the dim and shape

In [2]:
import numpy as np
import pandas as pd
a1 = np.array([[1,2,3],[3,4,5]])
a1

array([[1, 2, 3],
       [3, 4, 5]])

In [4]:
a1.shape

(2, 3)

In [6]:
type(a1)

numpy.ndarray

In [14]:
#Create an array of 20 numbers using arange function and slice the values between 10 to 15

l1 = np.arange(20)
a1 = l1[10:16]
a1

array([10, 11, 12, 13, 14, 15])

In [15]:
#Create 2 arrays of 7X5 dimension and broadcast between the 2 arrays using

In [23]:
a1 = np.array([[1,2,3,4,5],[7,8,9,12,11],[6,7,8,9,3],[12,2,4,7,9],[3,4,5,8,9],[6,0,2,8,9],[2,4,3,1,4]])
a2 = np.array([[4,5,6,7,8],[0,8,9,7,9],[1,1,1,1,1],[45,3,5,7,2],[11,12,13,13,2],[3,4,2,3,4],[9,0,8,0,3]])

print(a1+a2)
print(a1-a2)
print(a1*a2)
print(a1/a2)

[[ 5  7  9 11 13]
 [ 7 16 18 19 20]
 [ 7  8  9 10  4]
 [57  5  9 14 11]
 [14 16 18 21 11]
 [ 9  4  4 11 13]
 [11  4 11  1  7]]
[[ -3  -3  -3  -3  -3]
 [  7   0   0   5   2]
 [  5   6   7   8   2]
 [-33  -1  -1   0   7]
 [ -8  -8  -8  -5   7]
 [  3  -4   0   5   5]
 [ -7   4  -5   1   1]]
[[  4  10  18  28  40]
 [  0  64  81  84  99]
 [  6   7   8   9   3]
 [540   6  20  49  18]
 [ 33  48  65 104  18]
 [ 18   0   4  24  36]
 [ 18   0  24   0  12]]
[[0.25       0.4        0.5        0.57142857 0.625     ]
 [       inf 1.         1.         1.71428571 1.22222222]
 [6.         7.         8.         9.         3.        ]
 [0.26666667 0.66666667 0.8        1.         4.5       ]
 [0.27272727 0.33333333 0.38461538 0.61538462 4.5       ]
 [2.         0.         1.         2.66666667 2.25      ]
 [0.22222222        inf 0.375             inf 1.33333333]]


<ipython-input-23-498d2019a336>:7: RuntimeWarning: divide by zero encountered in true_divide
  print(a1/a2)


In [24]:
#Create 2 incompatible arrays for broadcast and print out the error
a1 = np.array([[1,2,3],[3,4,5]])
a2 = np.array([[1,2],[2,3]])

print(a1+a2)

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [5]:
#Create two arrays of any dimension and perform vstack and hstack
a1 = np.array([[1,2,3,4,5],[7,8,9,12,11]])
a2 = np.array([[4,5,6,7,8],[0,8,9,7,9]])
vresult = np.vstack((a1,a2))
hresult = np.hstack((a1,a2))
print(vresult)
print(hresult)


[[ 1  2  3  4  5]
 [ 7  8  9 12 11]
 [ 4  5  6  7  8]
 [ 0  8  9  7  9]]
[[ 1  2  3  4  5  4  5  6  7  8]
 [ 7  8  9 12 11  0  8  9  7  9]]


In [10]:
#Append two arrays using axis = 0 and axis = 1

a1 = np.array([[1,2,3,4,5],[7,8,9,12,11]])
a2 = np.array([[4,5,6,7,8],[0,8,9,7,9]])

print(np.append(a1,a2,axis = 0))
print(np.append(a1,a2,axis = 1))

[[ 1  2  3  4  5]
 [ 7  8  9 12 11]
 [ 4  5  6  7  8]
 [ 0  8  9  7  9]]
[[ 1  2  3  4  5  4  5  6  7  8]
 [ 7  8  9 12 11  0  8  9  7  9]]


In [12]:
#Create a dataframe for 8 X 4 dimension using list of lists and name the columns while dataframe creation

a1 = np.array([[1,2,3,4,5],[7,8,9,12,11],[6,7,8,9,3],[12,2,4,7,9],[3,4,5,8,9],[6,0,2,8,9],[2,4,3,1,4]])

df = pd.DataFrame(a1,columns=['col1','col2','col3','col4','col5'])
df

col1  col2  col3  col4  col5
0     1     2     3     4     5
1     7     8     9    12    11
2     6     7     8     9     3
3    12     2     4     7     9
4     3     4     5     8     9
5     6     0     2     8     9
6     2     4     3     1     4

In [15]:
#Create a dataframe of 4 X 8 dimension using a dictionary

dic = {'city':['hyd','blr','pun','chn','kol','del','mum'],
      'state':['TS','KA','MH','TN','WB','DEL','MH'],
      'pop':[10,14,7,15,11,12,20]}
df = pd.DataFrame(dic)
df

city state  pop
0  hyd    TS   10
1  blr    KA   14
2  pun    MH    7
3  chn    TN   15
4  kol    WB   11
5  del   DEL   12
6  mum    MH   20

In [19]:
#Use loc and iloc to subset the data for the above dataframe

df.loc[:3,['state','pop']]

state  pop
0    TS   10
1    KA   14
2    MH    7
3    TN   15

In [23]:
df.iloc[:4,1:3]

state  pop
0    TS   10
1    KA   14
2    MH    7
3    TN   15

In [36]:
#How to check the total number of not null values in a column

dic = {'city':['hyd','blr','pun','chn','kol','del','mum'],
      'state':['TS','KA','MH','TN',np.nan,'DEL','MH'],
      'pop':[10,14,7,15,np.nan,12,20]}
df1 = pd.DataFrame(dic)
df1

city state   pop
0  hyd    TS  10.0
1  blr    KA  14.0
2  pun    MH   7.0
3  chn    TN  15.0
4  kol   NaN   NaN
5  del   DEL  12.0
6  mum    MH  20.0

In [37]:
df1['state'].notnull().sum()

6

In [35]:
#Create a dataframe with missing values and fill them all with 100

df1.fillna(100,inplace = True)
df1

city state    pop
0  hyd    TS   10.0
1  blr    KA   14.0
2  pun    MH    7.0
3  chn    TN   15.0
4  kol   100  100.0
5  del   DEL   12.0
6  mum    MH   20.0

In [38]:
#Create a dataframe with missing values and drop the null records

df1.dropna(subset = ['pop'])

city state   pop
0  hyd    TS  10.0
1  blr    KA  14.0
2  pun    MH   7.0
3  chn    TN  15.0
5  del   DEL  12.0
6  mum    MH  20.0

In [39]:
# Perform following aggregation task on below table


dict1 = {'age':[25,30,45,35,33,35,25,52,21,24,48,22,27,28,21,51,23],
        'hair color':['Black','Black','Red','Blond','Brown','Brown','Black','Brown','Blond','Blond','Black','Black','Brown','Black','Blond','Black','Brown'],
        'us region': ['Southwest','Northwest','Northeast','Southwest','Southwest','Northeast','Southwest','Southeast','Southwest','Northeast','Southwest','Southwest','Northeast','Southeast','Southeast','Northwest','Southeast'],
        'validation':[1,1,1,0,0,0,0,0,1,0,1,0,0,1,1,0,1]}

df2 = pd.DataFrame(dict1)
df2

age hair color  us region  validation
0    25      Black  Southwest           1
1    30      Black  Northwest           1
2    45        Red  Northeast           1
3    35      Blond  Southwest           0
4    33      Brown  Southwest           0
5    35      Brown  Northeast           0
6    25      Black  Southwest           0
7    52      Brown  Southeast           0
8    21      Blond  Southwest           1
9    24      Blond  Northeast           0
10   48      Black  Southwest           1
11   22      Black  Southwest           0
12   27      Brown  Northeast           0
13   28      Black  Southeast           1
14   21      Blond  Southeast           1
15   51      Black  Northwest           0
16   23      Brown  Southeast           1

In [53]:
# a. Get the average age group by Regrion
 df2.groupby(['us region'])['age'].mean()


us region
Northeast    32.750000
Northwest    40.500000
Southeast    31.000000
Southwest    29.857143
Name: age, dtype: float64

In [52]:
#b.Get the sum of Age and Validation group by Hair color and then reset the index
result = df2.groupby(['hair color']).sum()
result

age  validation
hair color                 
Black       229           4
Blond       101           2
Brown       170           1
Red          45           1

In [49]:
#c.Get the man and the median of Age group by Region

df2.groupby(['us region'])['age'].agg([np.mean,np.median])

mean  median
us region                   
Northeast  32.750000    31.0
Northwest  40.500000    40.5
Southeast  31.000000    25.5
Southwest  29.857143    25.0

In [56]:

# Split the below table into half and perform merge (inner, left and right) on Region. One example for each type of merge (inner, left and right)

example for each type of merge (inner, left and right)
tab1 = {'age':[25,30,45,35,33,35,25,52,21],
        'hair color':['Black','Black','Red','Blond','Brown','Brown','Black','Brown','Blond'],
        'us region': ['Southwest','Northwest','Northeast','Southwest','Southwest','Northeast','Southwest','Southeast','Southwest'],
        'validation':[1,1,1,0,0,0,0,0,1]}

tab2 = {'age':[24,48,22,27,28,21,51,23],
        'hair color':['Blond','Black','Black','Brown','Black','Blond','Black','Brown'],
        'us region': ['Northeast','Southwest','Southwest','Northeast','Southeast','Southeast','Northwest','Southeast'],
        'validation':[0,1,0,0,1,1,0,1]}

df3 = pd.DataFrame(tab1)
df3
df4 = pd.DataFrame(tab2)
df4

age hair color  us region  validation
0   24      Blond  Northeast           0
1   48      Black  Southwest           1
2   22      Black  Southwest           0
3   27      Brown  Northeast           0
4   28      Black  Southeast           1
5   21      Blond  Southeast           1
6   51      Black  Northwest           0
7   23      Brown  Southeast           1

In [60]:
new_df = pd.merge(df3,df4,how = 'left', on = ['validation','age'])
new_df

age hair color_x us region_x  validation hair color_y us region_y
0   25        Black   Southwest           1          NaN         NaN
1   30        Black   Northwest           1          NaN         NaN
2   45          Red   Northeast           1          NaN         NaN
3   35        Blond   Southwest           0          NaN         NaN
4   33        Brown   Southwest           0          NaN         NaN
5   35        Brown   Northeast           0          NaN         NaN
6   25        Black   Southwest           0          NaN         NaN
7   52        Brown   Southeast           0          NaN         NaN
8   21        Blond   Southwest           1        Blond   Southeast

In [61]:
new_df = pd.merge(df3,df4,how = 'right', on = ['validation','age'])
new_df

age hair color_x us region_x  validation hair color_y us region_y
0   24          NaN         NaN           0        Blond   Northeast
1   48          NaN         NaN           1        Black   Southwest
2   22          NaN         NaN           0        Black   Southwest
3   27          NaN         NaN           0        Brown   Northeast
4   28          NaN         NaN           1        Black   Southeast
5   21        Blond   Southwest           1        Blond   Southeast
6   51          NaN         NaN           0        Black   Northwest
7   23          NaN         NaN           1        Brown   Southeast

In [62]:
new_df = pd.merge(df3,df4,how = 'inner', on = ['validation','age'])
new_df

age hair color_x us region_x  validation hair color_y us region_y
0   21        Blond   Southwest           1        Blond   Southeast

In [68]:
# Split the below table and perform concat row wise and column wise

new_concat_1 = pd.concat([df3,df4],axis = 1)
new_concat_1

age hair color  us region  validation   age hair color  us region  \
0   25      Black  Southwest           1  24.0      Blond  Northeast   
1   30      Black  Northwest           1  48.0      Black  Southwest   
2   45        Red  Northeast           1  22.0      Black  Southwest   
3   35      Blond  Southwest           0  27.0      Brown  Northeast   
4   33      Brown  Southwest           0  28.0      Black  Southeast   
5   35      Brown  Northeast           0  21.0      Blond  Southeast   
6   25      Black  Southwest           0  51.0      Black  Northwest   
7   52      Brown  Southeast           0  23.0      Brown  Southeast   
8   21      Blond  Southwest           1   NaN        NaN        NaN   

   validation  
0         0.0  
1         1.0  
2         0.0  
3         0.0  
4         1.0  
5         1.0  
6         0.0  
7         1.0  
8         NaN

In [71]:
new_concat_0 = pd.concat([df3,df4],axis = 0,ignore_index = True)
new_concat_0

age hair color  us region  validation
0    25      Black  Southwest           1
1    30      Black  Northwest           1
2    45        Red  Northeast           1
3    35      Blond  Southwest           0
4    33      Brown  Southwest           0
5    35      Brown  Northeast           0
6    25      Black  Southwest           0
7    52      Brown  Southeast           0
8    21      Blond  Southwest           1
9    24      Blond  Northeast           0
10   48      Black  Southwest           1
11   22      Black  Southwest           0
12   27      Brown  Northeast           0
13   28      Black  Southeast           1
14   21      Blond  Southeast           1
15   51      Black  Northwest           0
16   23      Brown  Southeast           1