In [1]:
v1 = int(input('enter first value'))
v2 = int(input('enter second value'))

def addvar(v1+v2):
    return v1+v2

SyntaxError: invalid syntax (<ipython-input-1-40f67b7e96e6>, line 4)

In [ ]:
addvar(2,3)

In [3]:
1+'p'

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [4]:
'p'+1

TypeError: can only concatenate str (not "int") to str

In [7]:
word = 'Data Scienc'

print('s' in word)


False


In [2]:
l1 = [10, 20, 33, 46, 55]

l1 = list(filter(lambda x: x%5 == 0,l1))
print(l1)

[10, 20, 55]


In [ ]:
a1 = int(input('enter first value'))
b1 = int(input('enter second value'))

def addsub(a1,b1):
    return a1+b1, a1-b1

In [ ]:
addsub(2,3)

## Assignment - 3

In [24]:
from zmy_pkg import maths

In [25]:
maths.calc.factorial(5)

120

In [26]:
maths.calc.degree_cel(32)

89.6

In [50]:

def fibonacci(n):
    a=0
    b=1
    count = 0
    if n<0:
        print('wrong input')
    elif n==0:
        return 0
    elif n==1:
        return 1
    else:
        while count < n:  
            print(a)  
            c = a + b  
            a = b  
            b = c  
            count += 1 

In [51]:
fibonacci(9)

0
1
1
2
3
5
8
13
21


In [55]:
l1 = list(range(10))

iter1 = reversed(l1)

for i in range(len(l1)):
    print(next(iter1))

9
8
7
6
5
4
3
2
1
0


### Assignment 4 (numpy & pandas)

In [1]:
# Create a 2D array and print the dim and shape

In [2]:
import numpy as np
import pandas as pd
a1 = np.array([[1,2,3],[3,4,5]])
a1

array([[1, 2, 3],
       [3, 4, 5]])

In [4]:
a1.shape

(2, 3)

In [6]:
type(a1)

numpy.ndarray

In [14]:
#Create an array of 20 numbers using arange function and slice the values between 10 to 15

l1 = np.arange(20)
a1 = l1[10:16]
a1

array([10, 11, 12, 13, 14, 15])

In [15]:
#Create 2 arrays of 7X5 dimension and broadcast between the 2 arrays using

In [23]:
a1 = np.array([[1,2,3,4,5],[7,8,9,12,11],[6,7,8,9,3],[12,2,4,7,9],[3,4,5,8,9],[6,0,2,8,9],[2,4,3,1,4]])
a2 = np.array([[4,5,6,7,8],[0,8,9,7,9],[1,1,1,1,1],[45,3,5,7,2],[11,12,13,13,2],[3,4,2,3,4],[9,0,8,0,3]])

print(a1+a2)
print(a1-a2)
print(a1*a2)
print(a1/a2)

[[ 5  7  9 11 13]
 [ 7 16 18 19 20]
 [ 7  8  9 10  4]
 [57  5  9 14 11]
 [14 16 18 21 11]
 [ 9  4  4 11 13]
 [11  4 11  1  7]]
[[ -3  -3  -3  -3  -3]
 [  7   0   0   5   2]
 [  5   6   7   8   2]
 [-33  -1  -1   0   7]
 [ -8  -8  -8  -5   7]
 [  3  -4   0   5   5]
 [ -7   4  -5   1   1]]
[[  4  10  18  28  40]
 [  0  64  81  84  99]
 [  6   7   8   9   3]
 [540   6  20  49  18]
 [ 33  48  65 104  18]
 [ 18   0   4  24  36]
 [ 18   0  24   0  12]]
[[0.25       0.4        0.5        0.57142857 0.625     ]
 [       inf 1.         1.         1.71428571 1.22222222]
 [6.         7.         8.         9.         3.        ]
 [0.26666667 0.66666667 0.8        1.         4.5       ]
 [0.27272727 0.33333333 0.38461538 0.61538462 4.5       ]
 [2.         0.         1.         2.66666667 2.25      ]
 [0.22222222        inf 0.375             inf 1.33333333]]


<ipython-input-23-498d2019a336>:7: RuntimeWarning: divide by zero encountered in true_divide
  print(a1/a2)


In [24]:
#Create 2 incompatible arrays for broadcast and print out the error
a1 = np.array([[1,2,3],[3,4,5]])
a2 = np.array([[1,2],[2,3]])

print(a1+a2)

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [5]:
#Create two arrays of any dimension and perform vstack and hstack
a1 = np.array([[1,2,3,4,5],[7,8,9,12,11]])
a2 = np.array([[4,5,6,7,8],[0,8,9,7,9]])
vresult = np.vstack((a1,a2))
hresult = np.hstack((a1,a2))
print(vresult)
print(hresult)


[[ 1  2  3  4  5]
 [ 7  8  9 12 11]
 [ 4  5  6  7  8]
 [ 0  8  9  7  9]]
[[ 1  2  3  4  5  4  5  6  7  8]
 [ 7  8  9 12 11  0  8  9  7  9]]


In [10]:
#Append two arrays using axis = 0 and axis = 1

a1 = np.array([[1,2,3,4,5],[7,8,9,12,11]])
a2 = np.array([[4,5,6,7,8],[0,8,9,7,9]])

print(np.append(a1,a2,axis = 0))
print(np.append(a1,a2,axis = 1))

[[ 1  2  3  4  5]
 [ 7  8  9 12 11]
 [ 4  5  6  7  8]
 [ 0  8  9  7  9]]
[[ 1  2  3  4  5  4  5  6  7  8]
 [ 7  8  9 12 11  0  8  9  7  9]]


In [12]:
#Create a dataframe for 8 X 4 dimension using list of lists and name the columns while dataframe creation

a1 = np.array([[1,2,3,4,5],[7,8,9,12,11],[6,7,8,9,3],[12,2,4,7,9],[3,4,5,8,9],[6,0,2,8,9],[2,4,3,1,4]])

df = pd.DataFrame(a1,columns=['col1','col2','col3','col4','col5'])
df

col1  col2  col3  col4  col5
0     1     2     3     4     5
1     7     8     9    12    11
2     6     7     8     9     3
3    12     2     4     7     9
4     3     4     5     8     9
5     6     0     2     8     9
6     2     4     3     1     4

In [15]:
#Create a dataframe of 4 X 8 dimension using a dictionary

dic = {'city':['hyd','blr','pun','chn','kol','del','mum'],
      'state':['TS','KA','MH','TN','WB','DEL','MH'],
      'pop':[10,14,7,15,11,12,20]}
df = pd.DataFrame(dic)
df

city state  pop
0  hyd    TS   10
1  blr    KA   14
2  pun    MH    7
3  chn    TN   15
4  kol    WB   11
5  del   DEL   12
6  mum    MH   20

In [19]:
#Use loc and iloc to subset the data for the above dataframe

df.loc[:3,['state','pop']]

state  pop
0    TS   10
1    KA   14
2    MH    7
3    TN   15

In [23]:
df.iloc[:4,1:3]

state  pop
0    TS   10
1    KA   14
2    MH    7
3    TN   15

In [36]:
#How to check the total number of not null values in a column

dic = {'city':['hyd','blr','pun','chn','kol','del','mum'],
      'state':['TS','KA','MH','TN',np.nan,'DEL','MH'],
      'pop':[10,14,7,15,np.nan,12,20]}
df1 = pd.DataFrame(dic)
df1

city state   pop
0  hyd    TS  10.0
1  blr    KA  14.0
2  pun    MH   7.0
3  chn    TN  15.0
4  kol   NaN   NaN
5  del   DEL  12.0
6  mum    MH  20.0

In [37]:
df1['state'].notnull().sum()

6

In [35]:
#Create a dataframe with missing values and fill them all with 100

df1.fillna(100,inplace = True)
df1

city state    pop
0  hyd    TS   10.0
1  blr    KA   14.0
2  pun    MH    7.0
3  chn    TN   15.0
4  kol   100  100.0
5  del   DEL   12.0
6  mum    MH   20.0

In [38]:
#Create a dataframe with missing values and drop the null records

df1.dropna(subset = ['pop'])

city state   pop
0  hyd    TS  10.0
1  blr    KA  14.0
2  pun    MH   7.0
3  chn    TN  15.0
5  del   DEL  12.0
6  mum    MH  20.0

In [39]:
# Perform following aggregation task on below table


dict1 = {'age':[25,30,45,35,33,35,25,52,21,24,48,22,27,28,21,51,23],
        'hair color':['Black','Black','Red','Blond','Brown','Brown','Black','Brown','Blond','Blond','Black','Black','Brown','Black','Blond','Black','Brown'],
        'us region': ['Southwest','Northwest','Northeast','Southwest','Southwest','Northeast','Southwest','Southeast','Southwest','Northeast','Southwest','Southwest','Northeast','Southeast','Southeast','Northwest','Southeast'],
        'validation':[1,1,1,0,0,0,0,0,1,0,1,0,0,1,1,0,1]}

df2 = pd.DataFrame(dict1)
df2

age hair color  us region  validation
0    25      Black  Southwest           1
1    30      Black  Northwest           1
2    45        Red  Northeast           1
3    35      Blond  Southwest           0
4    33      Brown  Southwest           0
5    35      Brown  Northeast           0
6    25      Black  Southwest           0
7    52      Brown  Southeast           0
8    21      Blond  Southwest           1
9    24      Blond  Northeast           0
10   48      Black  Southwest           1
11   22      Black  Southwest           0
12   27      Brown  Northeast           0
13   28      Black  Southeast           1
14   21      Blond  Southeast           1
15   51      Black  Northwest           0
16   23      Brown  Southeast           1

In [53]:
# a. Get the average age group by Regrion
 df2.groupby(['us region'])['age'].mean()


us region
Northeast    32.750000
Northwest    40.500000
Southeast    31.000000
Southwest    29.857143
Name: age, dtype: float64

In [52]:
#b.Get the sum of Age and Validation group by Hair color and then reset the index
result = df2.groupby(['hair color']).sum()
result

age  validation
hair color                 
Black       229           4
Blond       101           2
Brown       170           1
Red          45           1

In [49]:
#c.Get the man and the median of Age group by Region

df2.groupby(['us region'])['age'].agg([np.mean,np.median])

mean  median
us region                   
Northeast  32.750000    31.0
Northwest  40.500000    40.5
Southeast  31.000000    25.5
Southwest  29.857143    25.0

In [56]:

# Split the below table into half and perform merge (inner, left and right) on Region. One example for each type of merge (inner, left and right)

example for each type of merge (inner, left and right)
tab1 = {'age':[25,30,45,35,33,35,25,52,21],
        'hair color':['Black','Black','Red','Blond','Brown','Brown','Black','Brown','Blond'],
        'us region': ['Southwest','Northwest','Northeast','Southwest','Southwest','Northeast','Southwest','Southeast','Southwest'],
        'validation':[1,1,1,0,0,0,0,0,1]}

tab2 = {'age':[24,48,22,27,28,21,51,23],
        'hair color':['Blond','Black','Black','Brown','Black','Blond','Black','Brown'],
        'us region': ['Northeast','Southwest','Southwest','Northeast','Southeast','Southeast','Northwest','Southeast'],
        'validation':[0,1,0,0,1,1,0,1]}

df3 = pd.DataFrame(tab1)
df3
df4 = pd.DataFrame(tab2)
df4

age hair color  us region  validation
0   24      Blond  Northeast           0
1   48      Black  Southwest           1
2   22      Black  Southwest           0
3   27      Brown  Northeast           0
4   28      Black  Southeast           1
5   21      Blond  Southeast           1
6   51      Black  Northwest           0
7   23      Brown  Southeast           1

In [60]:
new_df = pd.merge(df3,df4,how = 'left', on = ['validation','age'])
new_df

age hair color_x us region_x  validation hair color_y us region_y
0   25        Black   Southwest           1          NaN         NaN
1   30        Black   Northwest           1          NaN         NaN
2   45          Red   Northeast           1          NaN         NaN
3   35        Blond   Southwest           0          NaN         NaN
4   33        Brown   Southwest           0          NaN         NaN
5   35        Brown   Northeast           0          NaN         NaN
6   25        Black   Southwest           0          NaN         NaN
7   52        Brown   Southeast           0          NaN         NaN
8   21        Blond   Southwest           1        Blond   Southeast

In [61]:
new_df = pd.merge(df3,df4,how = 'right', on = ['validation','age'])
new_df

age hair color_x us region_x  validation hair color_y us region_y
0   24          NaN         NaN           0        Blond   Northeast
1   48          NaN         NaN           1        Black   Southwest
2   22          NaN         NaN           0        Black   Southwest
3   27          NaN         NaN           0        Brown   Northeast
4   28          NaN         NaN           1        Black   Southeast
5   21        Blond   Southwest           1        Blond   Southeast
6   51          NaN         NaN           0        Black   Northwest
7   23          NaN         NaN           1        Brown   Southeast

In [62]:
new_df = pd.merge(df3,df4,how = 'inner', on = ['validation','age'])
new_df

age hair color_x us region_x  validation hair color_y us region_y
0   21        Blond   Southwest           1        Blond   Southeast

In [68]:
# Split the below table and perform concat row wise and column wise

new_concat_1 = pd.concat([df3,df4],axis = 1)
new_concat_1

age hair color  us region  validation   age hair color  us region  \
0   25      Black  Southwest           1  24.0      Blond  Northeast   
1   30      Black  Northwest           1  48.0      Black  Southwest   
2   45        Red  Northeast           1  22.0      Black  Southwest   
3   35      Blond  Southwest           0  27.0      Brown  Northeast   
4   33      Brown  Southwest           0  28.0      Black  Southeast   
5   35      Brown  Northeast           0  21.0      Blond  Southeast   
6   25      Black  Southwest           0  51.0      Black  Northwest   
7   52      Brown  Southeast           0  23.0      Brown  Southeast   
8   21      Blond  Southwest           1   NaN        NaN        NaN   

   validation  
0         0.0  
1         1.0  
2         0.0  
3         0.0  
4         1.0  
5         1.0  
6         0.0  
7         1.0  
8         NaN

In [71]:
new_concat_0 = pd.concat([df3,df4],axis = 0,ignore_index = True)
new_concat_0

age hair color  us region  validation
0    25      Black  Southwest           1
1    30      Black  Northwest           1
2    45        Red  Northeast           1
3    35      Blond  Southwest           0
4    33      Brown  Southwest           0
5    35      Brown  Northeast           0
6    25      Black  Southwest           0
7    52      Brown  Southeast           0
8    21      Blond  Southwest           1
9    24      Blond  Northeast           0
10   48      Black  Southwest           1
11   22      Black  Southwest           0
12   27      Brown  Northeast           0
13   28      Black  Southeast           1
14   21      Blond  Southeast           1
15   51      Black  Northwest           0
16   23      Brown  Southeast           1

### Preprocessing Assignment


In [2]:
import os
import numpy as np
import pandas as pd

In [5]:
os.chdir(r'C:\Personal\Py')
os.getcwd()

'C:\\Personal\\Py'

In [6]:
#1. Read the demand transaction file and print the first 15 rows and dtypes
df = pd.read_csv('Demand_txn.csv')
df[:15]

City Mapped_Sales_Type  Mapped_Item_Code Transaction_Date  \
0   Hyderabad         Take Away              9978        7/31/2018   
1   Hyderabad         Take Away              4064        7/31/2018   
2   Hyderabad         Main Hall               965        7/31/2018   
3   Hyderabad           Express              9978        7/31/2018   
4   Hyderabad           Express              1045        7/31/2018   
5   Hyderabad          Delivery              4056        7/31/2018   
6   Hyderabad         Take Away              4065        7/31/2018   
7   Hyderabad           Express              4058        7/31/2018   
8   Hyderabad           Express              4057        7/31/2018   
9   Hyderabad           Express              4056        7/31/2018   
10  Hyderabad          Delivery              4061        7/31/2018   
11  Hyderabad           Express              4055        7/31/2018   
12  Hyderabad         Take Away              4061        7/31/2018   
13  Hyderabad           Dine-in              9978        7/31/2018   
14  Hyderabad           Dine-in               979        7/31/2018   

    Quantity_Sold  Median_Price  Average_Tax_Percent  Effective_Price  \
0             167         187.0                 0.05       163.700000   
1             368         602.0                 0.05       584.329105   
2             694         263.0                 0.05       244.835163   
3             140         263.0                 0.05       243.500000   
4             139         392.0                 0.05       378.960000   
5             617         322.0                 0.05       305.354585   
6             217         652.0                 0.05       651.958113   
7             115         312.0                 0.05       294.960000   
8             113         312.0                 0.05       294.960000   
9             120         392.0                 0.05       378.955556   
10            144         942.0                 0.05       942.631515   
11            122         362.0                 0.05       347.458182   
12            233         802.0                 0.05       809.456066   
13            118         263.0                 0.05       243.500000   
14            164        1222.0                 0.05      1250.460000   

    Percent_Quantity_With_Discount  Avg_Discount_Percent_On_Discounted_Items  \
0                              NaN                                       NaN   
1                         0.027237                                  1.050000   
2                              NaN                                       NaN   
3                              NaN                                       NaN   
4                              NaN                                       NaN   
5                         0.003953                                  0.105020   
6                              NaN                                       NaN   
7                              NaN                                       NaN   
8                              NaN                                       NaN   
9                              NaN                                       NaN   
10                        0.151515                                  0.105006   
11                             NaN                                       NaN   
12                             NaN                                       NaN   
13                             NaN                                       NaN   
14                             NaN                                       NaN   

    ...  Day  Car_sales F_and_B_Inflation  \
0   ...  Tue    7559.28             143.7   
1   ...  Tue    7559.28             143.7   
2   ...  Tue    7559.28             143.7   
3   ...  Tue    7559.28             143.7   
4   ...  Tue    7559.28             143.7   
5   ...  Tue    7559.28             143.7   
6   ...  Tue    7559.28             143.7   
7   ...  Tue    7559.28             143.7   
8   ...  Tue    7559.28          

In [16]:
df.shape

(30231, 22)

In [10]:
df.dtypes

City                                           object
Mapped_Sales_Type                              object
Mapped_Item_Code                                int64
Transaction_Date                               object
Quantity_Sold                                   int64
Median_Price                                  float64
Average_Tax_Percent                           float64
Effective_Price                               float64
Percent_Quantity_With_Discount                float64
Avg_Discount_Percent_On_Discounted_Items      float64
Year                                            int64
Month                                           int64
Day                                            object
Car_sales                                     float64
F_and_B_Inflation                             float64
F_and_B_Inflation_Adjusted_Effective_Price    float64
F_and_B_Inflation_Adjusted_Median_Price       float64
First_Week_Of_The_Month_Dummy                   int64
Last_Week_Of_The_Month_Dummy

In [11]:
#2. Convert the transaction date column to a date column using pd.to_datetime function
df['Transaction_Date'] = pd.to_datetime(df['Transaction_Date'])

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30231 entries, 0 to 30230
Data columns (total 22 columns):
 #   Column                                      Non-Null Count  Dtype         
---  ------                                      --------------  -----         
 0   City                                        30231 non-null  object        
 1   Mapped_Sales_Type                           30231 non-null  object        
 2   Mapped_Item_Code                            30231 non-null  int64         
 3   Transaction_Date                            30231 non-null  datetime64[ns]
 4   Quantity_Sold                               30231 non-null  int64         
 5   Median_Price                                30231 non-null  float64       
 6   Average_Tax_Percent                         30231 non-null  float64       
 7   Effective_Price                             30229 non-null  float64       
 8   Percent_Quantity_With_Discount              12209 non-null  float64       
 9   Avg_Di

In [15]:
#3. Subset the dataframe for transaction date greater than '2016-08-01'
x_tx = df[df['Transaction_Date'] > '2016-08-01']
x_tx

City Mapped_Sales_Type  Mapped_Item_Code Transaction_Date  \
0      Hyderabad         Take Away              9978       2018-07-31   
1      Hyderabad         Take Away              4064       2018-07-31   
2      Hyderabad         Main Hall               965       2018-07-31   
3      Hyderabad           Express              9978       2018-07-31   
4      Hyderabad           Express              1045       2018-07-31   
...          ...               ...               ...              ...   
30187     Mumbai         Take Away              4059       2016-08-02   
30188     Mumbai         Main Hall               966       2016-08-02   
30189     Mumbai         Take Away              4065       2016-08-02   
30190     Mumbai          Delivery              4057       2016-08-02   
30191     Mumbai         Take Away              4061       2016-08-02   

       Quantity_Sold  Median_Price  Average_Tax_Percent  Effective_Price  \
0                167        187.00                 0.05       163.700000   
1                368        602.00                 0.05       584.329105   
2                694        263.00                 0.05       244.835163   
3                140        263.00                 0.05       243.500000   
4                139        392.00                 0.05       378.960000   
...              ...           ...                  ...              ...   
30187            519        300.00                 0.15       303.790980   
30188            369        238.85                 0.21       244.207519   
30189            234        510.00                 0.15       544.369268   
30190            145        227.00                 0.14       220.330000   
30191            216        658.00                 0.15       713.827429   

       Percent_Quantity_With_Discount  \
0                                 NaN   
1                            0.027237   
2                                 NaN   
3                                 NaN   
4                                 NaN   
...                               ...   
30187                        0.004902   
30188                             NaN   
30189                             NaN   
30190                             NaN   
30191                             NaN   

       Avg_Discount_Percent_On_Discounted_Items  ...  Day  Car_sales  \
0                                           NaN  ...  Tue    7559.28   
1                                      1.050000  ...  Tue    7559.28   
2                                           NaN  ...  Tue    7559.28   
3                                           NaN  ...  Tue    7559.28   
4                                           NaN  ...  Tue    7559.28   
...                                         ...  ...  ...        ...   
30187                                  0.114493  ...  Tue    8033.92   
30188                                       NaN  ...  Tue    8033.92   
30189                                       NaN  ...  Tue    8033.92   
30190                                       NaN  ...  Tue    8033.92   
30191                                       NaN  ...  Tue    8033.92   

      F_and_B_Inflation  F_and_B_Inflation_Adjusted_Effective_Price  \
0                 143.7                                    0.832985   
1                 143.7                                    3.760119   
2                 143.7                                    1.397600   
3                 143.7                                    1.388309   
4                 143.7                                    2.330967   
...                 ...                                         ...   
30187             140.1                                    1.854325   
30188             140.1                                    1.429033   
30189             140.1                                    3.571515   
30190             140.1                                    1.258601   
30191             140.1                                    4.781067   

       F_an

In [19]:
x_tx['Transaction_Date'].min()

Timestamp('2016-08-02 00:00:00')

In [20]:
#4. Look for unique values in Mapped_Sales_Type
x_tx['Mapped_Sales_Type'].unique()

array(['Take Away', 'Main Hall', 'Express', 'Delivery', 'Dine-in',
       'Bakery'], dtype=object)

In [23]:
# 5. Subset the entire dataframe, based on the below condition, to a new dataframe and work on the following questions
# a. Condition: Avg_Discount_Percent_On_Discounted_Items should be less than 1.0
# b. Check for sanity if the new dataframe contains Avg_Discount_Percent_On_Discounted_Items greater than or equal to 1.0

x_disc = df[df['Avg_Discount_Percent_On_Discounted_Items']<1]
x_disc['Avg_Discount_Percent_On_Discounted_Items'].max()

0.99793949

In [49]:
# 6. Groupby 'City', 'Mapped_Sales_Type', 'Mapped_Item_Code', 'Transaction_Date' and perform following aggregate operations on respective columns as mentioned (note: Only one groupby to do all the below aggregations)
# a. Quantity_Sold – sum
# b. Median_Price – median
# c. Effective_Price – median

agg_tb = df.groupby(['City','Mapped_Sales_Type', 'Mapped_Item_Code', 'Transaction_Date']).agg({'Quantity_Sold':sum,'Median_Price':np.median,'Effective_Price':np.median})  

agg_tb[:10]

Quantity_Sold  \
City    Mapped_Sales_Type Mapped_Item_Code Transaction_Date                  
Chennai Bakery            4057             2017-08-05                  110   
                          9978             2018-01-22                  105   
        Delivery          4055             2017-08-04                  377   
                                           2017-08-05                  377   
                                           2017-08-06                  638   
                                           2017-08-07                  393   
                                           2017-08-08                  320   
                                           2017-08-09                  514   
                                           2017-08-10                  405   
                                           2017-08-11                  468   

                                                             Median_Price  \
City    Mapped_Sales_Type Mapped_Item_Code Transaction_Date                 
Chennai Bakery            4057             2017-08-05               223.0   
                          9978             2018-01-22               178.0   
        Delivery          4055             2017-08-04               260.0   
                                           2017-08-05               260.0   
                                           2017-08-06               260.0   
                                           2017-08-07               260.0   
                                           2017-08-08               260.0   
                                           2017-08-09               260.0   
                                           2017-08-10               260.0   
                                           2017-08-11               260.0   

                                                             Effective_Price  
City    Mapped_Sales_Type Mapped_Item_Code Transaction_Date                   
Chennai Bakery            4057             2017-08-05             221.000000  
                          9978             2018-01-22             154.250000  
        Delivery          4055             2017-08-04             264.113759  
                                           2017-08-05             264.138571  
                                           2017-08-06             264.223814  
                                           2017-08-07             264.101702  
                                           2017-08-08             263.712153  
                                           2017-08-09             264.399256  
                                           2017-08-10             264.203878  
                                           2017-08-11             263.953389

In [61]:
#7. Display the data for Effective_Price = not null and just print the last 5 rows (hint: use .notnull function)

filtered_df = df[df['Effective_Price'].notnull()]
filtered_df.tail()


City Mapped_Sales_Type  Mapped_Item_Code Transaction_Date  \
30226  Mumbai         Take Away              4056       2016-08-01   
30227  Mumbai         Take Away              4058       2016-08-01   
30228  Mumbai           Dine-in               964       2016-08-01   
30229  Mumbai         Take Away              4066       2016-08-01   
30230  Mumbai          Delivery              4061       2016-08-01   

       Quantity_Sold  Median_Price  Average_Tax_Percent  Effective_Price  \
30226            615         239.0                 0.14       232.033552   
30227           1289         212.8                 0.14       202.575840   
30228            140         933.0                 0.21      1063.855517   
30229            179         501.0                 0.14       534.060000   
30230            117         716.5                 0.15       780.810000   

       Percent_Quantity_With_Discount  \
30226                        0.013889   
30227                        0.009338   
30228                             NaN   
30229                             NaN   
30230                             NaN   

       Avg_Discount_Percent_On_Discounted_Items  ...  Day  Car_sales  \
30226                                  0.883279  ...  Mon    8033.92   
30227                                  1.144999  ...  Mon    8033.92   
30228                                       NaN  ...  Mon    8033.92   
30229                                       NaN  ...  Mon    8033.92   
30230                                       NaN  ...  Mon    8033.92   

      F_and_B_Inflation  F_and_B_Inflation_Adjusted_Effective_Price  \
30226             140.1                                    1.342138   
30227             140.1                                    1.131876   
30228             140.1                                    7.279483   
30229             140.1                                    3.497930   
30230             140.1                                    5.259172   

       F_and_B_Inflation_Adjusted_Median_Price  First_Week_Of_The_Month_Dummy  \
30226                                 1.184868                              1   
30227                                 0.997859                              1   
30228                                 6.138473                              1   
30229                                 3.054961                              1   
30230                                 4.593148                              1   

       Last_Week_Of_The_Month_Dummy  Day_Of_The_Week_Seasonality  \
30226                             0                         0.78   
30227                             0                         0.78   
30228                             0                         0.77   
30229                             0                         0.66   
30230                             0                         0.61   

       Month_Of_The_Year_Seasonality  Two_Wheeler_sales  
30226                           0.99            27870.4  
30227                           0.99            27870.4  
30228                           0.94            27870.4  
30229                           0.99            27870.4  
30230                           0.89            27870.4  

[5 rows x 22 columns]

In [68]:
#8. Display the data for city = Chennai AND Mapped_Sales_Type = Delivery and print top 5 records 
# (hint use loc function to subset, then “&” operator to filter both the above cities)

display(df.loc[(df['City']=='Chennai') & (df['Mapped_Sales_Type'] == 'Delivery')] )

City Mapped_Sales_Type  Mapped_Item_Code Transaction_Date  \
8379   Chennai          Delivery              4055       2018-02-05   
8384   Chennai          Delivery              4068       2018-02-05   
8387   Chennai          Delivery              4064       2018-02-05   
8388   Chennai          Delivery              4058       2018-02-05   
8392   Chennai          Delivery              4061       2018-02-05   
...        ...               ...               ...              ...   
16606  Chennai          Delivery              4057       2017-08-04   
16609  Chennai          Delivery              4056       2017-08-04   
16611  Chennai          Delivery              4059       2017-08-04   
16612  Chennai          Delivery              4063       2017-08-04   
16614  Chennai          Delivery              4066       2017-08-04   

       Quantity_Sold  Median_Price  Average_Tax_Percent  Effective_Price  \
8379             544        281.10                 0.05       262.502194   
8384             129        566.43                 0.05       562.110000   
8387             186        619.34                 0.05       617.659733   
8388             287        259.19                 0.05       239.381307   
8392             128        850.62                 0.05       855.697647   
...              ...           ...                  ...              ...   
16606            143        242.00                 0.18       243.420000   
16609            200        269.00                 0.18       275.020225   
16611            272        349.00                 0.18       368.786211   
16612            130        708.00                 0.18       793.300000   
16614            116        588.00                 0.18       651.700000   

       Percent_Quantity_With_Discount  \
8379                              NaN   
8384                              NaN   
8387                              NaN   
8388                         0.005682   
8392                         0.058824   
...                               ...   
16606                             NaN   
16609                        0.011236   
16611                        0.024845   
16612                             NaN   
16614                             NaN   

       Avg_Discount_Percent_On_Discounted_Items  ...  Day  Car_sales  \
8379                                        NaN  ...  Mon    6660.16   
8384                                        NaN  ...  Mon    6660.16   
8387                                        NaN  ...  Mon    6660.16   
8388                                   0.105000  ...  Mon    6660.16   
8392                                   0.105000  ...  Mon    6660.16   
...                                         ...  ...  ...        ...   
16606                                       NaN  ...  Fri    8258.88   
16609                                  0.118010  ...  Fri    8258.88   
16611                                  0.118007  ...  Fri    8258.88   
16612                                       NaN  ...  Fri    8258.88   
16614                                       NaN  ...  Fri    8258.88   

      F_and_B_Inflation  F_and_B_Inflation_Adjusted_Effective_Price  \
8379              139.9                                    1.561846   
8384              139.9                                    3.703431   
8387              139.9                                    4.100498   
8388              139.9                                    1.396578   
8392              139.9                                    5.801985   
...                 ...                                         ...   
16606             143.8                                    1.386787   
16609             143.8                                    1.606538   
16611             143.8                                    2.258597   
16612             143.8                                    5.210709   
16614             143.8                                    4.226008   

       F_and_B_Inflation_Adjusted

In [ ]:
#9.  Display the data for the column “Day” with values Mon, Tue and Wed (hint: use .isin function)

In [69]:
#10. Display the data for Percent_Quantity_With_Discount not equal to 0.0 (hint: loc function with != operator)

df[df['Percent_Quantity_With_Discount'] != 0]

City Mapped_Sales_Type  Mapped_Item_Code Transaction_Date  \
0      Hyderabad         Take Away              9978       2018-07-31   
1      Hyderabad         Take Away              4064       2018-07-31   
2      Hyderabad         Main Hall               965       2018-07-31   
3      Hyderabad           Express              9978       2018-07-31   
4      Hyderabad           Express              1045       2018-07-31   
...          ...               ...               ...              ...   
30226     Mumbai         Take Away              4056       2016-08-01   
30227     Mumbai         Take Away              4058       2016-08-01   
30228     Mumbai           Dine-in               964       2016-08-01   
30229     Mumbai         Take Away              4066       2016-08-01   
30230     Mumbai          Delivery              4061       2016-08-01   

       Quantity_Sold  Median_Price  Average_Tax_Percent  Effective_Price  \
0                167         187.0                 0.05       163.700000   
1                368         602.0                 0.05       584.329105   
2                694         263.0                 0.05       244.835163   
3                140         263.0                 0.05       243.500000   
4                139         392.0                 0.05       378.960000   
...              ...           ...                  ...              ...   
30226            615         239.0                 0.14       232.033552   
30227           1289         212.8                 0.14       202.575840   
30228            140         933.0                 0.21      1063.855517   
30229            179         501.0                 0.14       534.060000   
30230            117         716.5                 0.15       780.810000   

       Percent_Quantity_With_Discount  \
0                                 NaN   
1                            0.027237   
2                                 NaN   
3                                 NaN   
4                                 NaN   
...                               ...   
30226                        0.013889   
30227                        0.009338   
30228                             NaN   
30229                             NaN   
30230                             NaN   

       Avg_Discount_Percent_On_Discounted_Items  ...  Day  Car_sales  \
0                                           NaN  ...  Tue    7559.28   
1                                      1.050000  ...  Tue    7559.28   
2                                           NaN  ...  Tue    7559.28   
3                                           NaN  ...  Tue    7559.28   
4                                           NaN  ...  Tue    7559.28   
...                                         ...  ...  ...        ...   
30226                                  0.883279  ...  Mon    8033.92   
30227                                  1.144999  ...  Mon    8033.92   
30228                                       NaN  ...  Mon    8033.92   
30229                                       NaN  ...  Mon    8033.92   
30230                                       NaN  ...  Mon    8033.92   

      F_and_B_Inflation  F_and_B_Inflation_Adjusted_Effective_Price  \
0                 143.7                                    0.832985   
1                 143.7                                    3.760119   
2                 143.7                                    1.397600   
3                 143.7                                    1.388309   
4                 143.7                                    2.330967   
...                 ...                                         ...   
30226             140.1                                    1.342138   
30227             140.1                                    1.131876   
30228             140.1                                    7.279483   
30229             140.1                                    3.497930   
30230             140.1                                    5.259172   

       F_an

In [70]:
df.shape

(30231, 22)

In [72]:
#11. Add a column “Range” to the existing dataframe for below condition
# a. 1 for Effective_Price > 500
# b. 0.5 otherwise

df['Range'] = [1 if i >= 500 else 0.5 for i in df['Effective_Price']]
df

City Mapped_Sales_Type  Mapped_Item_Code Transaction_Date  \
0      Hyderabad         Take Away              9978       2018-07-31   
1      Hyderabad         Take Away              4064       2018-07-31   
2      Hyderabad         Main Hall               965       2018-07-31   
3      Hyderabad           Express              9978       2018-07-31   
4      Hyderabad           Express              1045       2018-07-31   
...          ...               ...               ...              ...   
30226     Mumbai         Take Away              4056       2016-08-01   
30227     Mumbai         Take Away              4058       2016-08-01   
30228     Mumbai           Dine-in               964       2016-08-01   
30229     Mumbai         Take Away              4066       2016-08-01   
30230     Mumbai          Delivery              4061       2016-08-01   

       Quantity_Sold  Median_Price  Average_Tax_Percent  Effective_Price  \
0                167         187.0                 0.05       163.700000   
1                368         602.0                 0.05       584.329105   
2                694         263.0                 0.05       244.835163   
3                140         263.0                 0.05       243.500000   
4                139         392.0                 0.05       378.960000   
...              ...           ...                  ...              ...   
30226            615         239.0                 0.14       232.033552   
30227           1289         212.8                 0.14       202.575840   
30228            140         933.0                 0.21      1063.855517   
30229            179         501.0                 0.14       534.060000   
30230            117         716.5                 0.15       780.810000   

       Percent_Quantity_With_Discount  \
0                                 NaN   
1                            0.027237   
2                                 NaN   
3                                 NaN   
4                                 NaN   
...                               ...   
30226                        0.013889   
30227                        0.009338   
30228                             NaN   
30229                             NaN   
30230                             NaN   

       Avg_Discount_Percent_On_Discounted_Items  ...  Car_sales  \
0                                           NaN  ...    7559.28   
1                                      1.050000  ...    7559.28   
2                                           NaN  ...    7559.28   
3                                           NaN  ...    7559.28   
4                                           NaN  ...    7559.28   
...                                         ...  ...        ...   
30226                                  0.883279  ...    8033.92   
30227                                  1.144999  ...    8033.92   
30228                                       NaN  ...    8033.92   
30229                                       NaN  ...    8033.92   
30230                                       NaN  ...    8033.92   

       F_and_B_Inflation F_and_B_Inflation_Adjusted_Effective_Price  \
0                  143.7                                   0.832985   
1                  143.7                                   3.760119   
2                  143.7                                   1.397600   
3                  143.7                                   1.388309   
4                  143.7                                   2.330967   
...                  ...                                        ...   
30226              140.1                                   1.342138   
30227              140.1                                   1.131876   
30228              140.1                                   7.279483   
30229              140.1                                   3.497930   
30230              140.1                                   5.259172   

       F_and_B_Inflation_Adjusted_Median_Price  First_Week_Of_The_Month

In [73]:
# 12. Read the demand transaction file again and perform following operations for practice
# a. Handle the missing values in the column Percent_Quantity_With_Discount with strategy = mean
# b. One hot encode the columns Mapped_Sales_Type 
# c. Label binarize the column Day

df1 = pd.read_csv('Demand_txn.csv')
df1[:12]

City Mapped_Sales_Type  Mapped_Item_Code Transaction_Date  \
0   Hyderabad         Take Away              9978        7/31/2018   
1   Hyderabad         Take Away              4064        7/31/2018   
2   Hyderabad         Main Hall               965        7/31/2018   
3   Hyderabad           Express              9978        7/31/2018   
4   Hyderabad           Express              1045        7/31/2018   
5   Hyderabad          Delivery              4056        7/31/2018   
6   Hyderabad         Take Away              4065        7/31/2018   
7   Hyderabad           Express              4058        7/31/2018   
8   Hyderabad           Express              4057        7/31/2018   
9   Hyderabad           Express              4056        7/31/2018   
10  Hyderabad          Delivery              4061        7/31/2018   
11  Hyderabad           Express              4055        7/31/2018   

    Quantity_Sold  Median_Price  Average_Tax_Percent  Effective_Price  \
0             167         187.0                 0.05       163.700000   
1             368         602.0                 0.05       584.329105   
2             694         263.0                 0.05       244.835163   
3             140         263.0                 0.05       243.500000   
4             139         392.0                 0.05       378.960000   
5             617         322.0                 0.05       305.354585   
6             217         652.0                 0.05       651.958113   
7             115         312.0                 0.05       294.960000   
8             113         312.0                 0.05       294.960000   
9             120         392.0                 0.05       378.955556   
10            144         942.0                 0.05       942.631515   
11            122         362.0                 0.05       347.458182   

    Percent_Quantity_With_Discount  Avg_Discount_Percent_On_Discounted_Items  \
0                              NaN                                       NaN   
1                         0.027237                                  1.050000   
2                              NaN                                       NaN   
3                              NaN                                       NaN   
4                              NaN                                       NaN   
5                         0.003953                                  0.105020   
6                              NaN                                       NaN   
7                              NaN                                       NaN   
8                              NaN                                       NaN   
9                              NaN                                       NaN   
10                        0.151515                                  0.105006   
11                             NaN                                       NaN   

    ...  Day  Car_sales F_and_B_Inflation  \
0   ...  Tue    7559.28             143.7   
1   ...  Tue    7559.28             143.7   
2   ...  Tue    7559.28             143.7   
3   ...  Tue    7559.28             143.7   
4   ...  Tue    7559.28             143.7   
5   ...  Tue    7559.28             143.7   
6   ...  Tue    7559.28             143.7   
7   ...  Tue    7559.28             143.7   
8   ...  Tue    7559.28             143.7   
9   ...  Tue    7559.28             143.7   
10  ...  Tue    7559.28             143.7   
11  ...  Tue    7559.28             143.7   

    F_and_B_Inflation_Adjusted_Effective_Price  \
0                                     0.832985   
1                                     3.760119   
2                                     1.397600   
3                                     1.388309   
4                                     2.330967   
5                                     1.818751   
6                                     4.230745   
7                                     1.746416   
8                                     1.746416   
9                    

In [75]:
df1['Percent_Quantity_With_Discount'].isnull().sum()

18022

In [77]:
df1['Percent_Quantity_With_Discount'].fillna(df1['Percent_Quantity_With_Discount'].mean(), inplace = True)

In [78]:
df1

City Mapped_Sales_Type  Mapped_Item_Code Transaction_Date  \
0      Hyderabad         Take Away              9978        7/31/2018   
1      Hyderabad         Take Away              4064        7/31/2018   
2      Hyderabad         Main Hall               965        7/31/2018   
3      Hyderabad           Express              9978        7/31/2018   
4      Hyderabad           Express              1045        7/31/2018   
...          ...               ...               ...              ...   
30226     Mumbai         Take Away              4056         8/1/2016   
30227     Mumbai         Take Away              4058         8/1/2016   
30228     Mumbai           Dine-in               964         8/1/2016   
30229     Mumbai         Take Away              4066         8/1/2016   
30230     Mumbai          Delivery              4061         8/1/2016   

       Quantity_Sold  Median_Price  Average_Tax_Percent  Effective_Price  \
0                167         187.0                 0.05       163.700000   
1                368         602.0                 0.05       584.329105   
2                694         263.0                 0.05       244.835163   
3                140         263.0                 0.05       243.500000   
4                139         392.0                 0.05       378.960000   
...              ...           ...                  ...              ...   
30226            615         239.0                 0.14       232.033552   
30227           1289         212.8                 0.14       202.575840   
30228            140         933.0                 0.21      1063.855517   
30229            179         501.0                 0.14       534.060000   
30230            117         716.5                 0.15       780.810000   

       Percent_Quantity_With_Discount  \
0                            0.098011   
1                            0.027237   
2                            0.098011   
3                            0.098011   
4                            0.098011   
...                               ...   
30226                        0.013889   
30227                        0.009338   
30228                        0.098011   
30229                        0.098011   
30230                        0.098011   

       Avg_Discount_Percent_On_Discounted_Items  ...  Day  Car_sales  \
0                                           NaN  ...  Tue    7559.28   
1                                      1.050000  ...  Tue    7559.28   
2                                           NaN  ...  Tue    7559.28   
3                                           NaN  ...  Tue    7559.28   
4                                           NaN  ...  Tue    7559.28   
...                                         ...  ...  ...        ...   
30226                                  0.883279  ...  Mon    8033.92   
30227                                  1.144999  ...  Mon    8033.92   
30228                                       NaN  ...  Mon    8033.92   
30229                                       NaN  ...  Mon    8033.92   
30230                                       NaN  ...  Mon    8033.92   

      F_and_B_Inflation  F_and_B_Inflation_Adjusted_Effective_Price  \
0                 143.7                                    0.832985   
1                 143.7                                    3.760119   
2                 143.7                                    1.397600   
3                 143.7                                    1.388309   
4                 143.7                                    2.330967   
...                 ...                                         ...   
30226             140.1                                    1.342138   
30227             140.1                                    1.131876   
30228             140.1                                    7.279483   
30229             140.1                                    3.497930   
30230             140.1                                    5.259172   

       F_an

In [79]:
df1['Percent_Quantity_With_Discount'].isnull().sum()

0

In [80]:
df1['Mapped_Sales_Type'].value_counts()

Take Away    9812
Delivery     9469
Dine-in      5271
Main Hall    3529
Express      2061
Bakery         89
Name: Mapped_Sales_Type, dtype: int64

In [90]:
# b. One hot encode the columns Mapped_Sales_Type 
pd.get_dummies(df1,columns = ['Mapped_Sales_Type'], prefix='SalesType').head()


City  Mapped_Item_Code Transaction_Date  Quantity_Sold  Median_Price  \
0  Hyderabad              9978        7/31/2018            167         187.0   
1  Hyderabad              4064        7/31/2018            368         602.0   
2  Hyderabad               965        7/31/2018            694         263.0   
3  Hyderabad              9978        7/31/2018            140         263.0   
4  Hyderabad              1045        7/31/2018            139         392.0   

   Average_Tax_Percent  Effective_Price  Percent_Quantity_With_Discount  \
0                 0.05       163.700000                        0.098011   
1                 0.05       584.329105                        0.027237   
2                 0.05       244.835163                        0.098011   
3                 0.05       243.500000                        0.098011   
4                 0.05       378.960000                        0.098011   

   Avg_Discount_Percent_On_Discounted_Items  Year  ...  \
0                                       NaN  2018  ...   
1                                      1.05  2018  ...   
2                                       NaN  2018  ...   
3                                       NaN  2018  ...   
4                                       NaN  2018  ...   

   Last_Week_Of_The_Month_Dummy Day_Of_The_Week_Seasonality  \
0                             1                        0.86   
1                             1                        0.83   
2                             1                        1.08   
3                             1                        0.78   
4                             1                        0.73   

   Month_Of_The_Year_Seasonality  Two_Wheeler_sales  SalesType_Bakery  \
0                           0.91           37307.52                 0   
1                           0.91           37307.52                 0   
2                           1.08           37307.52                 0   
3                           0.08           37307.52                 0   
4                           0.08           37307.52                 0   

   SalesType_Delivery  SalesType_Dine-in  SalesType_Express  \
0                   0                  0                  0   
1                   0                  0                  0   
2                   0                  0                  0   
3                   0                  0                  1   
4                   0                  0                  1   

   SalesType_Main Hall  SalesType_Take Away  
0                    0                    1  
1                    0                    1  
2                    1                    0  
3                    0                    0  
4                    0                    0  

[5 rows x 27 columns]

In [107]:
# c. Label binarize the column Day
from sklearn.preprocessing import LabelBinarizer
lb_style = LabelBinarizer()
lb_result = lb_style.fit_transform(df1['Day'])
pd.DataFrame(lb_result,columns = lb_style.classes_).tail()

Fri  Mon  Sat  Sun  Thu  Tue  Wed
30226    0    1    0    0    0    0    0
30227    0    1    0    0    0    0    0
30228    0    1    0    0    0    0    0
30229    0    1    0    0    0    0    0
30230    0    1    0    0    0    0    0